The workshop will be conducted over two days.

**** First Day - Installation and REPL [1.5 hours | 6:30 PM to 8:00 PM]

We will go over installation on IDEs and setup of development
environment on all attendees laptops.
# TODO: check in-browser-evaluator

Once we are setup, one can [[https://github.com/nid90/clojurebridge-blr/archive/master.zip][download]] this repository on their
machines and open it in their editor of choice. The directory contains a file
called *bridge.clj*. This file has some very
basic opening content that one can evaluate, we'll build upon it as we
go through the lessons.

After installation, we will go over the following topics on the first day:
1. What is programming
2. What is Clojure
3. Why did we choose Clojure
4. Taster into a few Clojure things on the REPL

**** Second Day - Learning Clojure [7 hours | 10:30 AM to 5:30 PM]

First off, we will have the teachers do a quick double check for everyone's IDE and REPL setup from last evening.

The second day will be crash course in Clojure. We will divide the day into two parts - learning and doing.

***** Learning [3 hours | 10:30 AM - 1:30 PM]
In the learning section, we will go over the basics of Clojure in a presentation style while doing exercises as we come across them in the REPL. We have broken down the content into the following chapters:
1. Understanding the REPL [10 mins]
2. Syntax, or the anatomy of an s-expression [15 mins]
3. Simple data types - string, bool and numbers (infix vs. prefix notation) [20 mins]
4. Special data types - symbols and keywords (introduce def) [20 mins]
5. Functions (built-in fns, def, fn) [25 mins]
6. Sequence / Collection types and associated functions [30 mins]
7. Context and bindings (let) [20 mins]
8. Control flow and logic (if, when, do) [20 mins]
9. Composition of functions [15 mins]

***** Lunch [45 mins | 1:30 PM - 2:15 PM]

***** Doing [3 hours | 2:30 PM to 5:30 PM]
We will go over the exercises in the exercises folder in the repo - quidditch, land-of-wizards and mars-rover.

We can do these exercises in smaller groups with a teacher assigned to each group.
