* NASA needs your help controlling the rovers on Mars.

- A squad of robotic rovers are to be landed by NASA on a plateau on
  Mars.
- This plateau, which is curiously rectangular, must be navigated by
  the rovers so that their on board cameras can get a complete view of
  the surrounding terrain to send back to Earth.
- A rover's position is represented by a combination of an x and y
  co-ordinates and a letter representing one of the four cardinal
  compass points. The plateau is divided up into a grid to simplify
  navigation. An example position might be 0, 0, N, which means the
  rover is in the bottom left corner and facing North.
- In order to control a rover, NASA sends a simple string of
  letters. The possible letters are 'L', 'R' and 'M'. 'L' and 'R'
  makes the rover spin 90 degrees left or right respectively, without
  moving from its current spot.
- 'M' means move forward one grid point, and maintain the same
  heading.
- Assume that the square directly North from (x, y) is (x, y+1).

Input:

- Let's assume the plateau size is 10 units which makes the upper
  right coordinates of the plateau 9,9 and the lower left coordinates
  of the plateau 0,0.
- Start this exercise by placing one rover on the plateau. You should
  provide it's initial coordinates and the direction it is facing when
  placing the rover.
- Handle edge case scenarios. The rover should not be allowed to move
  off the plateau (no-op).
- Then add one more rover to the plateau and make sure the rovers
  don't collide. If a command causes a collision, it should not be
  executed.

- Ask your teacher how you should model the rover, its coordinates and
  the plateau if you are not sure.

Test Input (example signature and usage):
;; (place-rover 1 2 "N")
;;=> return the plateau with the rover on it
;; (move-rover "LMLMLMLMM")
;;=> return the final position of the rover after moving it (in this case 1 3 N)

;; (place-rover 3 3 "E")
;;=> return the plateau with the rover on it
;; (move-rover "MMRMMRMRRM")
;;=> return the final position of the rover after moving it (in this case 5 1 E)
